version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    env_file:
      - .env
    networks:
      - backend_net
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
  
    # تم التعديل ليربط بحسابك على دوكر هب
    build: ./backend
    image: mohamedali255/library-backend:latest 
    container_name: backend_container
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:${MONGO_PORT}/${DB_NAME}?authSource=admin
    depends_on:
      - mongodb
    networks:
      - frontend_net
      - backend_net
    restart: on-failure

  frontend:
  
    # تم التعديل ليربط بحسابك على دوكر هب
    build: ./frontend
    image: mohamedali255/library-frontend:latest
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - frontend_net
    restart: always

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  mongo-data: